# Generated by Django 6.0.6 on 2026-07-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macieira', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genotipo',
            name='identificador_unico',
            field=models.CharField(editable=False, max_length=50, unique=True, verbose_name='Identificador Único'),
        ),
        migrations.AlterField(
            model_name='historicalgenotipo',
            name='identificador_unico',
            field=models.CharField(db_index=True, editable=False, max_length=50, verbose_name='Identificador Único'),
        ),
    ]
