# Generated by Django 6.0.6 on 2026-07-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macieira', '0002_alter_genotipo_identificador_unico_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genotipo',
            name='alelos_s',
        ),
        migrations.RemoveField(
            model_name='historicalgenotipo',
            name='alelos_s',
        ),
        migrations.AddField(
            model_name='genotipo',
            name='alelo_s1',
            field=models.CharField(blank=True, choices=[('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3'), ('S4', 'S4'), ('S5', 'S5'), ('S6', 'S6'), ('S7', 'S7'), ('S8', 'S8'), ('S9', 'S9'), ('S10', 'S10'), ('S11', 'S11'), ('S12', 'S12'), ('S13', 'S13'), ('S14', 'S14'), ('S15', 'S15'), ('S16', 'S16'), ('S17', 'S17'), ('S18', 'S18'), ('S19', 'S19'), ('S20', 'S20'), ('S21', 'S21'), ('S22', 'S22'), ('S23', 'S23'), ('S24', 'S24'), ('S25', 'S25'), ('S26', 'S26'), ('S27', 'S27'), ('S28', 'S28'), ('S29', 'S29'), ('S30', 'S30')], max_length=5, null=True, verbose_name='Alelo S - primeiro'),
        ),
        migrations.AddField(
            model_name='genotipo',
            name='alelo_s2',
            field=models.CharField(blank=True, choices=[('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3'), ('S4', 'S4'), ('S5', 'S5'), ('S6', 'S6'), ('S7', 'S7'), ('S8', 'S8'), ('S9', 'S9'), ('S10', 'S10'), ('S11', 'S11'), ('S12', 'S12'), ('S13', 'S13'), ('S14', 'S14'), ('S15', 'S15'), ('S16', 'S16'), ('S17', 'S17'), ('S18', 'S18'), ('S19', 'S19'), ('S20', 'S20'), ('S21', 'S21'), ('S22', 'S22'), ('S23', 'S23'), ('S24', 'S24'), ('S25', 'S25'), ('S26', 'S26'), ('S27', 'S27'), ('S28', 'S28'), ('S29', 'S29'), ('S30', 'S30')], max_length=5, null=True, verbose_name='Alelo S - segundo'),
        ),
        migrations.AddField(
            model_name='historicalgenotipo',
            name='alelo_s1',
            field=models.CharField(blank=True, choices=[('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3'), ('S4', 'S4'), ('S5', 'S5'), ('S6', 'S6'), ('S7', 'S7'), ('S8', 'S8'), ('S9', 'S9'), ('S10', 'S10'), ('S11', 'S11'), ('S12', 'S12'), ('S13', 'S13'), ('S14', 'S14'), ('S15', 'S15'), ('S16', 'S16'), ('S17', 'S17'), ('S18', 'S18'), ('S19', 'S19'), ('S20', 'S20'), ('S21', 'S21'), ('S22', 'S22'), ('S23', 'S23'), ('S24', 'S24'), ('S25', 'S25'), ('S26', 'S26'), ('S27', 'S27'), ('S28', 'S28'), ('S29', 'S29'), ('S30', 'S30')], max_length=5, null=True, verbose_name='Alelo S - primeiro'),
        ),
        migrations.AddField(
            model_name='historicalgenotipo',
            name='alelo_s2',
            field=models.CharField(blank=True, choices=[('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3'), ('S4', 'S4'), ('S5', 'S5'), ('S6', 'S6'), ('S7', 'S7'), ('S8', 'S8'), ('S9', 'S9'), ('S10', 'S10'), ('S11', 'S11'), ('S12', 'S12'), ('S13', 'S13'), ('S14', 'S14'), ('S15', 'S15'), ('S16', 'S16'), ('S17', 'S17'), ('S18', 'S18'), ('S19', 'S19'), ('S20', 'S20'), ('S21', 'S21'), ('S22', 'S22'), ('S23', 'S23'), ('S24', 'S24'), ('S25', 'S25'), ('S26', 'S26'), ('S27', 'S27'), ('S28', 'S28'), ('S29', 'S29'), ('S30', 'S30')], max_length=5, null=True, verbose_name='Alelo S - segundo'),
        ),
    ]
