# Generated by Django 6.0.6 on 2026-07-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macieira', '0003_remove_genotipo_alelos_s_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cruzamento',
            name='num_bloco_hibridos',
            field=models.IntegerField(blank=True, null=True, verbose_name='N°. Plantas Levadas ao Bloco de Hibridos'),
        ),
        migrations.AddField(
            model_name='cruzamento',
            name='num_matrizeiro',
            field=models.IntegerField(blank=True, null=True, verbose_name='N° Plantas Levadas ao Matrizeiro'),
        ),
        migrations.AddField(
            model_name='cruzamento',
            name='num_plantulas_formadas',
            field=models.IntegerField(blank=True, null=True, verbose_name='N° Plantulas Formadas'),
        ),
        migrations.AddField(
            model_name='historicalcruzamento',
            name='num_bloco_hibridos',
            field=models.IntegerField(blank=True, null=True, verbose_name='N°. Plantas Levadas ao Bloco de Hibridos'),
        ),
        migrations.AddField(
            model_name='historicalcruzamento',
            name='num_matrizeiro',
            field=models.IntegerField(blank=True, null=True, verbose_name='N° Plantas Levadas ao Matrizeiro'),
        ),
        migrations.AddField(
            model_name='historicalcruzamento',
            name='num_plantulas_formadas',
            field=models.IntegerField(blank=True, null=True, verbose_name='N° Plantulas Formadas'),
        ),
    ]
