# Generated by Django 6.0.6 on 2026-07-02 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macieira', '0004_cruzamento_num_bloco_hibridos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genotipo',
            name='cruzamento_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='macieira.cruzamento', verbose_name='Cruzamento de Origem'),
        ),
        migrations.AddField(
            model_name='historicalgenotipo',
            name='cruzamento_origem',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='macieira.cruzamento', verbose_name='Cruzamento de Origem'),
        ),
    ]
