# Generated by Django 6.0.6 on 2026-07-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macieira', '0005_genotipo_cruzamento_origem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacaofenotipica',
            name='foto_frutos_colhidos',
            field=models.ImageField(blank=True, null=True, upload_to='avaliacoes/frutos/', verbose_name='Foto dos Frutos Colhidos'),
        ),
        migrations.AddField(
            model_name='avaliacaofenotipica',
            name='foto_sintomas',
            field=models.ImageField(blank=True, null=True, upload_to='avaliacoes/sintomas/', verbose_name='Foto de Sintomas'),
        ),
        migrations.AddField(
            model_name='genotipo',
            name='foto_fruto',
            field=models.ImageField(blank=True, null=True, upload_to='genotipos/frutos/', verbose_name='Foto do Fruto'),
        ),
        migrations.AddField(
            model_name='genotipo',
            name='foto_planta',
            field=models.ImageField(null=True, upload_to='genotipos/plantas/', verbose_name='Foto da Planta'),
        ),
        migrations.AddField(
            model_name='historicalavaliacaofenotipica',
            name='foto_frutos_colhidos',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Foto dos Frutos Colhidos'),
        ),
        migrations.AddField(
            model_name='historicalavaliacaofenotipica',
            name='foto_sintomas',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Foto de Sintomas'),
        ),
        migrations.AddField(
            model_name='historicalgenotipo',
            name='foto_fruto',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Foto do Fruto'),
        ),
        migrations.AddField(
            model_name='historicalgenotipo',
            name='foto_planta',
            field=models.TextField(max_length=100, null=True, verbose_name='Foto da Planta'),
        ),
    ]
