# Generated by Django 6.0.6 on 2026-07-02 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macieira', '0006_avaliacaofenotipica_foto_frutos_colhidos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genotipo',
            name='publicar_passaporte',
            field=models.BooleanField(default=False, verbose_name='Publicar Passaporte'),
        ),
        migrations.AddField(
            model_name='historicalgenotipo',
            name='publicar_passaporte',
            field=models.BooleanField(default=False, verbose_name='Publicar Passaporte'),
        ),
    ]
