# Generated by Django 6.0.6 on 2026-07-03 11:50

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macieira', '0007_genotipo_publicar_passaporte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacaofenotipica',
            name='incidencia_mfg',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('5.0'))], verbose_name='Incidência Mancha Foliar da Glomerella (0-5)'),
        ),
        migrations.AddField(
            model_name='historicalavaliacaofenotipica',
            name='incidencia_mfg',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('5.0'))], verbose_name='Incidência Mancha Foliar da Glomerella (0-5)'),
        ),
        migrations.AlterField(
            model_name='avaliacaofenotipica',
            name='incidencia_sarna',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('5.0'))], verbose_name='Incidência Sarna (0-5)'),
        ),
        migrations.AlterField(
            model_name='genotipo',
            name='foto_planta',
            field=models.ImageField(blank=True, null=True, upload_to='genotipos/plantas/', verbose_name='Foto da Planta'),
        ),
        migrations.AlterField(
            model_name='historicalavaliacaofenotipica',
            name='incidencia_sarna',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('5.0'))], verbose_name='Incidência Sarna (0-5)'),
        ),
        migrations.AlterField(
            model_name='historicalgenotipo',
            name='foto_planta',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Foto da Planta'),
        ),
    ]
