# Generated by Django 6.0.6 on 2026-07-03 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macieira', '0008_avaliacaofenotipica_incidencia_mfg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacaofenotipica',
            name='ambiente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='macieira.ambiente', verbose_name='Local da avaliação'),
        ),
        migrations.AddField(
            model_name='historicalavaliacaofenotipica',
            name='ambiente',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='macieira.ambiente', verbose_name='Local da avaliação'),
        ),
    ]
