# Generated by Django 6.0.6 on 2026-07-03 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macieira', '0009_avaliacaofenotipica_ambiente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaofenotipica',
            name='ambiente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='macieira.ambiente', verbose_name='Local da avaliação'),
        ),
    ]
