# Generated by Django 6.0.6 on 2026-07-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macieira', '0010_alter_avaliacaofenotipica_ambiente'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacaofenotipica',
            name='data_final_floracao',
            field=models.DateField(blank=True, null=True, verbose_name='Data Final Floração'),
        ),
        migrations.AddField(
            model_name='avaliacaofenotipica',
            name='data_inicio_brotacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data Inicio Brotação'),
        ),
        migrations.AddField(
            model_name='avaliacaofenotipica',
            name='data_inicio_floracao',
            field=models.DateField(blank=True, null=True, verbose_name='Data Inicio Floração'),
        ),
        migrations.AddField(
            model_name='avaliacaofenotipica',
            name='data_inicio_frutificacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data Inicio Frutificação'),
        ),
        migrations.AddField(
            model_name='historicalavaliacaofenotipica',
            name='data_final_floracao',
            field=models.DateField(blank=True, null=True, verbose_name='Data Final Floração'),
        ),
        migrations.AddField(
            model_name='historicalavaliacaofenotipica',
            name='data_inicio_brotacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data Inicio Brotação'),
        ),
        migrations.AddField(
            model_name='historicalavaliacaofenotipica',
            name='data_inicio_floracao',
            field=models.DateField(blank=True, null=True, verbose_name='Data Inicio Floração'),
        ),
        migrations.AddField(
            model_name='historicalavaliacaofenotipica',
            name='data_inicio_frutificacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data Inicio Frutificação'),
        ),
    ]
