# Generated by Django 6.0.6 on 2026-07-03 17:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macieira', '0011_avaliacaofenotipica_data_final_floracao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacaofenotipica',
            name='vigor',
        ),
        migrations.RemoveField(
            model_name='historicalavaliacaofenotipica',
            name='vigor',
        ),
        migrations.AddField(
            model_name='avaliacaofenotipica',
            name='cor_epiderme',
            field=models.CharField(blank=True, choices=[('VERMELHO', 'Vermelho'), ('AMARELO', 'Amarelo'), ('VERDE', 'Verde')], max_length=8, null=True, verbose_name='Cor da Epiderme'),
        ),
        migrations.AddField(
            model_name='avaliacaofenotipica',
            name='nota_calibre',
            field=models.DecimalField(blank=True, choices=[(Decimal('0.0'), '0.0'), (Decimal('0.5'), '0.5'), (Decimal('1.0'), '1.0'), (Decimal('1.5'), '1.5'), (Decimal('2.0'), '2.0'), (Decimal('2.5'), '2.5'), (Decimal('3.0'), '3.0'), (Decimal('3.5'), '3.5'), (Decimal('4.0'), '4.0'), (Decimal('4.5'), '4.5'), (Decimal('5.0'), '5.0')], decimal_places=1, max_digits=3, null=True, verbose_name='Nota Calibre (0-5)'),
        ),
        migrations.AddField(
            model_name='avaliacaofenotipica',
            name='nota_vigor',
            field=models.DecimalField(blank=True, choices=[(Decimal('0.0'), '0.0'), (Decimal('0.5'), '0.5'), (Decimal('1.0'), '1.0'), (Decimal('1.5'), '1.5'), (Decimal('2.0'), '2.0'), (Decimal('2.5'), '2.5'), (Decimal('3.0'), '3.0'), (Decimal('3.5'), '3.5'), (Decimal('4.0'), '4.0'), (Decimal('4.5'), '4.5'), (Decimal('5.0'), '5.0')], decimal_places=1, max_digits=3, null=True, verbose_name='Vigor'),
        ),
        migrations.AddField(
            model_name='historicalavaliacaofenotipica',
            name='cor_epiderme',
            field=models.CharField(blank=True, choices=[('VERMELHO', 'Vermelho'), ('AMARELO', 'Amarelo'), ('VERDE', 'Verde')], max_length=8, null=True, verbose_name='Cor da Epiderme'),
        ),
        migrations.AddField(
            model_name='historicalavaliacaofenotipica',
            name='nota_calibre',
            field=models.DecimalField(blank=True, choices=[(Decimal('0.0'), '0.0'), (Decimal('0.5'), '0.5'), (Decimal('1.0'), '1.0'), (Decimal('1.5'), '1.5'), (Decimal('2.0'), '2.0'), (Decimal('2.5'), '2.5'), (Decimal('3.0'), '3.0'), (Decimal('3.5'), '3.5'), (Decimal('4.0'), '4.0'), (Decimal('4.5'), '4.5'), (Decimal('5.0'), '5.0')], decimal_places=1, max_digits=3, null=True, verbose_name='Nota Calibre (0-5)'),
        ),
        migrations.AddField(
            model_name='historicalavaliacaofenotipica',
            name='nota_vigor',
            field=models.DecimalField(blank=True, choices=[(Decimal('0.0'), '0.0'), (Decimal('0.5'), '0.5'), (Decimal('1.0'), '1.0'), (Decimal('1.5'), '1.5'), (Decimal('2.0'), '2.0'), (Decimal('2.5'), '2.5'), (Decimal('3.0'), '3.0'), (Decimal('3.5'), '3.5'), (Decimal('4.0'), '4.0'), (Decimal('4.5'), '4.5'), (Decimal('5.0'), '5.0')], decimal_places=1, max_digits=3, null=True, verbose_name='Vigor'),
        ),
    ]
