# Generated by Django 6.0.6 on 2026-07-03 17:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macieira', '0012_remove_avaliacaofenotipica_vigor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacaofenotipica',
            name='nota_aparencia',
            field=models.DecimalField(blank=True, choices=[(Decimal('0.0'), '0.0'), (Decimal('0.5'), '0.5'), (Decimal('1.0'), '1.0'), (Decimal('1.5'), '1.5'), (Decimal('2.0'), '2.0'), (Decimal('2.5'), '2.5'), (Decimal('3.0'), '3.0'), (Decimal('3.5'), '3.5'), (Decimal('4.0'), '4.0'), (Decimal('4.5'), '4.5'), (Decimal('5.0'), '5.0')], decimal_places=1, max_digits=3, null=True, verbose_name='Nota Aparência (0 - 5)'),
        ),
        migrations.AddField(
            model_name='historicalavaliacaofenotipica',
            name='nota_aparencia',
            field=models.DecimalField(blank=True, choices=[(Decimal('0.0'), '0.0'), (Decimal('0.5'), '0.5'), (Decimal('1.0'), '1.0'), (Decimal('1.5'), '1.5'), (Decimal('2.0'), '2.0'), (Decimal('2.5'), '2.5'), (Decimal('3.0'), '3.0'), (Decimal('3.5'), '3.5'), (Decimal('4.0'), '4.0'), (Decimal('4.5'), '4.5'), (Decimal('5.0'), '5.0')], decimal_places=1, max_digits=3, null=True, verbose_name='Nota Aparência (0 - 5)'),
        ),
    ]
