# Generated by Django 6.0.6 on 2026-07-03 18:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macieira', '0013_avaliacaofenotipica_nota_aparencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacaofenotipica',
            name='abertura_tubo',
            field=models.CharField(blank=True, choices=[('AUSENTE', 'Ausente'), ('PRESENTE', 'Presente (em baixa intensidade)'), ('INTENSO', 'Muito Presente')], max_length=8, null=True, verbose_name='Abertura Tubo Polinico'),
        ),
        migrations.AddField(
            model_name='avaliacaofenotipica',
            name='cork_spot',
            field=models.CharField(blank=True, choices=[('AUSENTE', 'Ausente'), ('PRESENTE', 'Presente (em baixa intensidade)'), ('INTENSO', 'Muito Presente')], max_length=8, null=True, verbose_name='Presença de Cork Spot'),
        ),
        migrations.AddField(
            model_name='avaliacaofenotipica',
            name='def_peduncular',
            field=models.CharField(blank=True, choices=[('AUSENTE', 'Ausente'), ('PRESENTE', 'Presente (em baixa intensidade)'), ('INTENSO', 'Muito Presente')], max_length=8, null=True, verbose_name='Deformação Peduncular'),
        ),
        migrations.AddField(
            model_name='avaliacaofenotipica',
            name='nota_adistringencia',
            field=models.DecimalField(blank=True, choices=[(Decimal('0.0'), '0.0'), (Decimal('0.5'), '0.5'), (Decimal('1.0'), '1.0'), (Decimal('1.5'), '1.5'), (Decimal('2.0'), '2.0'), (Decimal('2.5'), '2.5'), (Decimal('3.0'), '3.0'), (Decimal('3.5'), '3.5'), (Decimal('4.0'), '4.0'), (Decimal('4.5'), '4.5'), (Decimal('5.0'), '5.0')], decimal_places=1, max_digits=3, null=True, verbose_name='Nota Adistringência (0-5)'),
        ),
        migrations.AddField(
            model_name='avaliacaofenotipica',
            name='nota_aroma',
            field=models.DecimalField(blank=True, choices=[(Decimal('0.0'), '0.0'), (Decimal('0.5'), '0.5'), (Decimal('1.0'), '1.0'), (Decimal('1.5'), '1.5'), (Decimal('2.0'), '2.0'), (Decimal('2.5'), '2.5'), (Decimal('3.0'), '3.0'), (Decimal('3.5'), '3.5'), (Decimal('4.0'), '4.0'), (Decimal('4.5'), '4.5'), (Decimal('5.0'), '5.0')], decimal_places=1, max_digits=3, null=True, verbose_name='Nota Aroma (0-5)'),
        ),
        migrations.AddField(
            model_name='avaliacaofenotipica',
            name='nota_balanco_acucar_acidez',
            field=models.DecimalField(blank=True, choices=[(Decimal('0.0'), '0.0'), (Decimal('0.5'), '0.5'), (Decimal('1.0'), '1.0'), (Decimal('1.5'), '1.5'), (Decimal('2.0'), '2.0'), (Decimal('2.5'), '2.5'), (Decimal('3.0'), '3.0'), (Decimal('3.5'), '3.5'), (Decimal('4.0'), '4.0'), (Decimal('4.5'), '4.5'), (Decimal('5.0'), '5.0')], decimal_places=1, max_digits=3, null=True, verbose_name='Nota Balanço Açucar / Acides (0-5)'),
        ),
        migrations.AddField(
            model_name='avaliacaofenotipica',
            name='nota_crocancia',
            field=models.DecimalField(blank=True, choices=[(Decimal('0.0'), '0.0'), (Decimal('0.5'), '0.5'), (Decimal('1.0'), '1.0'), (Decimal('1.5'), '1.5'), (Decimal('2.0'), '2.0'), (Decimal('2.5'), '2.5'), (Decimal('3.0'), '3.0'), (Decimal('3.5'), '3.5'), (Decimal('4.0'), '4.0'), (Decimal('4.5'), '4.5'), (Decimal('5.0'), '5.0')], decimal_places=1, max_digits=3, null=True, verbose_name='Nota Crocância (0-5)'),
        ),
        migrations.AddField(
            model_name='avaliacaofenotipica',
            name='nota_fineza',
            field=models.DecimalField(blank=True, choices=[(Decimal('0.0'), '0.0'), (Decimal('0.5'), '0.5'), (Decimal('1.0'), '1.0'), (Decimal('1.5'), '1.5'), (Decimal('2.0'), '2.0'), (Decimal('2.5'), '2.5'), (Decimal('3.0'), '3.0'), (Decimal('3.5'), '3.5'), (Decimal('4.0'), '4.0'), (Decimal('4.5'), '4.5'), (Decimal('5.0'), '5.0')], decimal_places=1, max_digits=3, null=True, verbose_name='Nota Fineza (0-5)'),
        ),
        migrations.AddField(
            model_name='avaliacaofenotipica',
            name='nota_firmeza',
            field=models.DecimalField(blank=True, choices=[(Decimal('0.0'), '0.0'), (Decimal('0.5'), '0.5'), (Decimal('1.0'), '1.0'), (Decimal('1.5'), '1.5'), (Decimal('2.0'), '2.0'), (Decimal('2.5'), '2.5'), (Decimal('3.0'), '3.0'), (Decimal('3.5'), '3.5'), (Decimal('4.0'), '4.0'), (Decimal('4.5'), '4.5'), (Decimal('5.0'), '5.0')], decimal_places=1, max_digits=3, null=True, verbose_name='Nota Firmeza (0-5)'),
        ),
        migrations.AddField(
            model_name='avaliacaofenotipica',
            name='nota_global',
            field=models.DecimalField(blank=True, choices=[(Decimal('0.0'), '0.0'), (Decimal('0.5'), '0.5'), (Decimal('1.0'), '1.0'), (Decimal('1.5'), '1.5'), (Decimal('2.0'), '2.0'), (Decimal('2.5'), '2.5'), (Decimal('3.0'), '3.0'), (Decimal('3.5'), '3.5'), (Decimal('4.0'), '4.0'), (Decimal('4.5'), '4.5'), (Decimal('5.0'), '5.0')], decimal_places=1, max_digits=3, null=True, verbose_name='Nota Global (0-5)'),
        ),
        migrations.AddField(
            model_name='avaliacaofenotipica',
            name='nota_sabor',
            field=models.DecimalField(blank=True, choices=[(Decimal('0.0'), '0.0'), (Decimal('0.5'), '0.5'), (Decimal('1.0'), '1.0'), (Decimal('1.5'), '1.5'), (Decimal('2.0'), '2.0'), (Decimal('2.5'), '2.5'), (Decimal('3.0'), '3.0'), (Decimal('3.5'), '3.5'), (Decimal('4.0'), '4.0'), (Decimal('4.5'), '4.5'), (Decimal('5.0'), '5.0')], decimal_places=1, max_digits=3, null=True, verbose_name='Nota Sabor (0-5)'),
        ),
        migrations.AddField(
            model_name='avaliacaofenotipica',
            name='nota_suculencia',
            field=models.DecimalField(blank=True, choices=[(Decimal('0.0'), '0.0'), (Decimal('0.5'), '0.5'), (Decimal('1.0'), '1.0'), (Decimal('1.5'), '1.5'), (Decimal('2.0'), '2.0'), (Decimal('2.5'), '2.5'), (Decimal('3.0'), '3.0'), (Decimal('3.5'), '3.5'), (Decimal('4.0'), '4.0'), (Decimal('4.5'), '4.5'), (Decimal('5.0'), '5.0')], decimal_places=1, max_digits=3, null=True, verbose_name='Nota Suculência (0-5)'),
        ),
        migrations.AddField(
            model_name='avaliacaofenotipica',
            name='pingo_mel',
            field=models.CharField(blank=True, choices=[('AUSENTE', 'Ausente'), ('PRESENTE', 'Presente (em baixa intensidade)'), ('INTENSO', 'Muito Presente')], max_length=8, null=True, verbose_name='Presença de Pingo de Mel'),
        ),
        migrations.AddField(
            model_name='avaliacaofenotipica',
            name='queda_pre_colheita',
            field=models.CharField(blank=True, choices=[('AUSENTE', 'Ausente'), ('PRESENTE', 'Presente (em baixa intensidade)'), ('INTENSO', 'Muito Presente')], max_length=8, null=True, verbose_name='Queda Pré-Colheita'),
        ),
        migrations.AddField(
            model_name='avaliacaofenotipica',
            name='queimadura_sol',
            field=models.CharField(blank=True, choices=[('AUSENTE', 'Ausente'), ('PRESENTE', 'Presente (em baixa intensidade)'), ('INTENSO', 'Muito Presente')], max_length=8, null=True, verbose_name='Queimadura de Sol'),
        ),
        migrations.AddField(
            model_name='avaliacaofenotipica',
            name='rachadura',
            field=models.CharField(blank=True, choices=[('AUSENTE', 'Ausente'), ('PRESENTE', 'Presente (em baixa intensidade)'), ('INTENSO', 'Muito Presente')], max_length=8, null=True, verbose_name='Rachadura'),
        ),
        migrations.AddField(
            model_name='avaliacaofenotipica',
            name='russting',
            field=models.CharField(blank=True, choices=[('AUSENTE', 'Ausente'), ('PRESENTE', 'Presente (em baixa intensidade)'), ('INTENSO', 'Muito Presente')], max_length=8, null=True, verbose_name='Presença de Russting'),
        ),
        migrations.AddField(
            model_name='historicalavaliacaofenotipica',
            name='abertura_tubo',
            field=models.CharField(blank=True, choices=[('AUSENTE', 'Ausente'), ('PRESENTE', 'Presente (em baixa intensidade)'), ('INTENSO', 'Muito Presente')], max_length=8, null=True, verbose_name='Abertura Tubo Polinico'),
        ),
        migrations.AddField(
            model_name='historicalavaliacaofenotipica',
            name='cork_spot',
            field=models.CharField(blank=True, choices=[('AUSENTE', 'Ausente'), ('PRESENTE', 'Presente (em baixa intensidade)'), ('INTENSO', 'Muito Presente')], max_length=8, null=True, verbose_name='Presença de Cork Spot'),
        ),
        migrations.AddField(
            model_name='historicalavaliacaofenotipica',
            name='def_peduncular',
            field=models.CharField(blank=True, choices=[('AUSENTE', 'Ausente'), ('PRESENTE', 'Presente (em baixa intensidade)'), ('INTENSO', 'Muito Presente')], max_length=8, null=True, verbose_name='Deformação Peduncular'),
        ),
        migrations.AddField(
            model_name='historicalavaliacaofenotipica',
            name='nota_adistringencia',
            field=models.DecimalField(blank=True, choices=[(Decimal('0.0'), '0.0'), (Decimal('0.5'), '0.5'), (Decimal('1.0'), '1.0'), (Decimal('1.5'), '1.5'), (Decimal('2.0'), '2.0'), (Decimal('2.5'), '2.5'), (Decimal('3.0'), '3.0'), (Decimal('3.5'), '3.5'), (Decimal('4.0'), '4.0'), (Decimal('4.5'), '4.5'), (Decimal('5.0'), '5.0')], decimal_places=1, max_digits=3, null=True, verbose_name='Nota Adistringência (0-5)'),
        ),
        migrations.AddField(
            model_name='historicalavaliacaofenotipica',
            name='nota_aroma',
            field=models.DecimalField(blank=True, choices=[(Decimal('0.0'), '0.0'), (Decimal('0.5'), '0.5'), (Decimal('1.0'), '1.0'), (Decimal('1.5'), '1.5'), (Decimal('2.0'), '2.0'), (Decimal('2.5'), '2.5'), (Decimal('3.0'), '3.0'), (Decimal('3.5'), '3.5'), (Decimal('4.0'), '4.0'), (Decimal('4.5'), '4.5'), (Decimal('5.0'), '5.0')], decimal_places=1, max_digits=3, null=True, verbose_name='Nota Aroma (0-5)'),
        ),
        migrations.AddField(
            model_name='historicalavaliacaofenotipica',
            name='nota_balanco_acucar_acidez',
            field=models.DecimalField(blank=True, choices=[(Decimal('0.0'), '0.0'), (Decimal('0.5'), '0.5'), (Decimal('1.0'), '1.0'), (Decimal('1.5'), '1.5'), (Decimal('2.0'), '2.0'), (Decimal('2.5'), '2.5'), (Decimal('3.0'), '3.0'), (Decimal('3.5'), '3.5'), (Decimal('4.0'), '4.0'), (Decimal('4.5'), '4.5'), (Decimal('5.0'), '5.0')], decimal_places=1, max_digits=3, null=True, verbose_name='Nota Balanço Açucar / Acides (0-5)'),
        ),
        migrations.AddField(
            model_name='historicalavaliacaofenotipica',
            name='nota_crocancia',
            field=models.DecimalField(blank=True, choices=[(Decimal('0.0'), '0.0'), (Decimal('0.5'), '0.5'), (Decimal('1.0'), '1.0'), (Decimal('1.5'), '1.5'), (Decimal('2.0'), '2.0'), (Decimal('2.5'), '2.5'), (Decimal('3.0'), '3.0'), (Decimal('3.5'), '3.5'), (Decimal('4.0'), '4.0'), (Decimal('4.5'), '4.5'), (Decimal('5.0'), '5.0')], decimal_places=1, max_digits=3, null=True, verbose_name='Nota Crocância (0-5)'),
        ),
        migrations.AddField(
            model_name='historicalavaliacaofenotipica',
            name='nota_fineza',
            field=models.DecimalField(blank=True, choices=[(Decimal('0.0'), '0.0'), (Decimal('0.5'), '0.5'), (Decimal('1.0'), '1.0'), (Decimal('1.5'), '1.5'), (Decimal('2.0'), '2.0'), (Decimal('2.5'), '2.5'), (Decimal('3.0'), '3.0'), (Decimal('3.5'), '3.5'), (Decimal('4.0'), '4.0'), (Decimal('4.5'), '4.5'), (Decimal('5.0'), '5.0')], decimal_places=1, max_digits=3, null=True, verbose_name='Nota Fineza (0-5)'),
        ),
        migrations.AddField(
            model_name='historicalavaliacaofenotipica',
            name='nota_firmeza',
            field=models.DecimalField(blank=True, choices=[(Decimal('0.0'), '0.0'), (Decimal('0.5'), '0.5'), (Decimal('1.0'), '1.0'), (Decimal('1.5'), '1.5'), (Decimal('2.0'), '2.0'), (Decimal('2.5'), '2.5'), (Decimal('3.0'), '3.0'), (Decimal('3.5'), '3.5'), (Decimal('4.0'), '4.0'), (Decimal('4.5'), '4.5'), (Decimal('5.0'), '5.0')], decimal_places=1, max_digits=3, null=True, verbose_name='Nota Firmeza (0-5)'),
        ),
        migrations.AddField(
            model_name='historicalavaliacaofenotipica',
            name='nota_global',
            field=models.DecimalField(blank=True, choices=[(Decimal('0.0'), '0.0'), (Decimal('0.5'), '0.5'), (Decimal('1.0'), '1.0'), (Decimal('1.5'), '1.5'), (Decimal('2.0'), '2.0'), (Decimal('2.5'), '2.5'), (Decimal('3.0'), '3.0'), (Decimal('3.5'), '3.5'), (Decimal('4.0'), '4.0'), (Decimal('4.5'), '4.5'), (Decimal('5.0'), '5.0')], decimal_places=1, max_digits=3, null=True, verbose_name='Nota Global (0-5)'),
        ),
        migrations.AddField(
            model_name='historicalavaliacaofenotipica',
            name='nota_sabor',
            field=models.DecimalField(blank=True, choices=[(Decimal('0.0'), '0.0'), (Decimal('0.5'), '0.5'), (Decimal('1.0'), '1.0'), (Decimal('1.5'), '1.5'), (Decimal('2.0'), '2.0'), (Decimal('2.5'), '2.5'), (Decimal('3.0'), '3.0'), (Decimal('3.5'), '3.5'), (Decimal('4.0'), '4.0'), (Decimal('4.5'), '4.5'), (Decimal('5.0'), '5.0')], decimal_places=1, max_digits=3, null=True, verbose_name='Nota Sabor (0-5)'),
        ),
        migrations.AddField(
            model_name='historicalavaliacaofenotipica',
            name='nota_suculencia',
            field=models.DecimalField(blank=True, choices=[(Decimal('0.0'), '0.0'), (Decimal('0.5'), '0.5'), (Decimal('1.0'), '1.0'), (Decimal('1.5'), '1.5'), (Decimal('2.0'), '2.0'), (Decimal('2.5'), '2.5'), (Decimal('3.0'), '3.0'), (Decimal('3.5'), '3.5'), (Decimal('4.0'), '4.0'), (Decimal('4.5'), '4.5'), (Decimal('5.0'), '5.0')], decimal_places=1, max_digits=3, null=True, verbose_name='Nota Suculência (0-5)'),
        ),
        migrations.AddField(
            model_name='historicalavaliacaofenotipica',
            name='pingo_mel',
            field=models.CharField(blank=True, choices=[('AUSENTE', 'Ausente'), ('PRESENTE', 'Presente (em baixa intensidade)'), ('INTENSO', 'Muito Presente')], max_length=8, null=True, verbose_name='Presença de Pingo de Mel'),
        ),
        migrations.AddField(
            model_name='historicalavaliacaofenotipica',
            name='queda_pre_colheita',
            field=models.CharField(blank=True, choices=[('AUSENTE', 'Ausente'), ('PRESENTE', 'Presente (em baixa intensidade)'), ('INTENSO', 'Muito Presente')], max_length=8, null=True, verbose_name='Queda Pré-Colheita'),
        ),
        migrations.AddField(
            model_name='historicalavaliacaofenotipica',
            name='queimadura_sol',
            field=models.CharField(blank=True, choices=[('AUSENTE', 'Ausente'), ('PRESENTE', 'Presente (em baixa intensidade)'), ('INTENSO', 'Muito Presente')], max_length=8, null=True, verbose_name='Queimadura de Sol'),
        ),
        migrations.AddField(
            model_name='historicalavaliacaofenotipica',
            name='rachadura',
            field=models.CharField(blank=True, choices=[('AUSENTE', 'Ausente'), ('PRESENTE', 'Presente (em baixa intensidade)'), ('INTENSO', 'Muito Presente')], max_length=8, null=True, verbose_name='Rachadura'),
        ),
        migrations.AddField(
            model_name='historicalavaliacaofenotipica',
            name='russting',
            field=models.CharField(blank=True, choices=[('AUSENTE', 'Ausente'), ('PRESENTE', 'Presente (em baixa intensidade)'), ('INTENSO', 'Muito Presente')], max_length=8, null=True, verbose_name='Presença de Russting'),
        ),
    ]
