# Generated by Django 6.0.6 on 2026-07-03 18:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macieira', '0014_avaliacaofenotipica_abertura_tubo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacaofenotipica',
            name='fruto_cacho',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')], null=True, verbose_name='Quantidade de Frutos por Cacho (1-9)'),
        ),
        migrations.AddField(
            model_name='avaliacaofenotipica',
            name='nota_brotacao',
            field=models.DecimalField(blank=True, choices=[(Decimal('0.0'), '0.0'), (Decimal('0.5'), '0.5'), (Decimal('1.0'), '1.0'), (Decimal('1.5'), '1.5'), (Decimal('2.0'), '2.0'), (Decimal('2.5'), '2.5'), (Decimal('3.0'), '3.0'), (Decimal('3.5'), '3.5'), (Decimal('4.0'), '4.0'), (Decimal('4.5'), '4.5'), (Decimal('5.0'), '5.0')], decimal_places=1, max_digits=3, null=True, verbose_name='Nota Brotação (0-5)'),
        ),
        migrations.AddField(
            model_name='avaliacaofenotipica',
            name='nota_burrknots',
            field=models.DecimalField(blank=True, choices=[(Decimal('0.0'), '0.0'), (Decimal('0.5'), '0.5'), (Decimal('1.0'), '1.0'), (Decimal('1.5'), '1.5'), (Decimal('2.0'), '2.0'), (Decimal('2.5'), '2.5'), (Decimal('3.0'), '3.0'), (Decimal('3.5'), '3.5'), (Decimal('4.0'), '4.0'), (Decimal('4.5'), '4.5'), (Decimal('5.0'), '5.0')], decimal_places=1, max_digits=3, null=True, verbose_name='Nota Burrknots (0-5)'),
        ),
        migrations.AddField(
            model_name='avaliacaofenotipica',
            name='nota_esporonamento',
            field=models.DecimalField(blank=True, choices=[(Decimal('0.0'), '0.0'), (Decimal('0.5'), '0.5'), (Decimal('1.0'), '1.0'), (Decimal('1.5'), '1.5'), (Decimal('2.0'), '2.0'), (Decimal('2.5'), '2.5'), (Decimal('3.0'), '3.0'), (Decimal('3.5'), '3.5'), (Decimal('4.0'), '4.0'), (Decimal('4.5'), '4.5'), (Decimal('5.0'), '5.0')], decimal_places=1, max_digits=3, null=True, verbose_name='Nota Esporonamento (0-5)'),
        ),
        migrations.AddField(
            model_name='avaliacaofenotipica',
            name='nota_fruit_set',
            field=models.DecimalField(blank=True, choices=[(Decimal('0.0'), '0.0'), (Decimal('0.5'), '0.5'), (Decimal('1.0'), '1.0'), (Decimal('1.5'), '1.5'), (Decimal('2.0'), '2.0'), (Decimal('2.5'), '2.5'), (Decimal('3.0'), '3.0'), (Decimal('3.5'), '3.5'), (Decimal('4.0'), '4.0'), (Decimal('4.5'), '4.5'), (Decimal('5.0'), '5.0')], decimal_places=1, max_digits=3, null=True, verbose_name='Nota Fruit Set (0-5)'),
        ),
        migrations.AddField(
            model_name='avaliacaofenotipica',
            name='nota_producao',
            field=models.DecimalField(blank=True, choices=[(Decimal('0.0'), '0.0'), (Decimal('0.5'), '0.5'), (Decimal('1.0'), '1.0'), (Decimal('1.5'), '1.5'), (Decimal('2.0'), '2.0'), (Decimal('2.5'), '2.5'), (Decimal('3.0'), '3.0'), (Decimal('3.5'), '3.5'), (Decimal('4.0'), '4.0'), (Decimal('4.5'), '4.5'), (Decimal('5.0'), '5.0')], decimal_places=1, max_digits=3, null=True, verbose_name='Nota Produção (0-5)'),
        ),
        migrations.AddField(
            model_name='historicalavaliacaofenotipica',
            name='fruto_cacho',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')], null=True, verbose_name='Quantidade de Frutos por Cacho (1-9)'),
        ),
        migrations.AddField(
            model_name='historicalavaliacaofenotipica',
            name='nota_brotacao',
            field=models.DecimalField(blank=True, choices=[(Decimal('0.0'), '0.0'), (Decimal('0.5'), '0.5'), (Decimal('1.0'), '1.0'), (Decimal('1.5'), '1.5'), (Decimal('2.0'), '2.0'), (Decimal('2.5'), '2.5'), (Decimal('3.0'), '3.0'), (Decimal('3.5'), '3.5'), (Decimal('4.0'), '4.0'), (Decimal('4.5'), '4.5'), (Decimal('5.0'), '5.0')], decimal_places=1, max_digits=3, null=True, verbose_name='Nota Brotação (0-5)'),
        ),
        migrations.AddField(
            model_name='historicalavaliacaofenotipica',
            name='nota_burrknots',
            field=models.DecimalField(blank=True, choices=[(Decimal('0.0'), '0.0'), (Decimal('0.5'), '0.5'), (Decimal('1.0'), '1.0'), (Decimal('1.5'), '1.5'), (Decimal('2.0'), '2.0'), (Decimal('2.5'), '2.5'), (Decimal('3.0'), '3.0'), (Decimal('3.5'), '3.5'), (Decimal('4.0'), '4.0'), (Decimal('4.5'), '4.5'), (Decimal('5.0'), '5.0')], decimal_places=1, max_digits=3, null=True, verbose_name='Nota Burrknots (0-5)'),
        ),
        migrations.AddField(
            model_name='historicalavaliacaofenotipica',
            name='nota_esporonamento',
            field=models.DecimalField(blank=True, choices=[(Decimal('0.0'), '0.0'), (Decimal('0.5'), '0.5'), (Decimal('1.0'), '1.0'), (Decimal('1.5'), '1.5'), (Decimal('2.0'), '2.0'), (Decimal('2.5'), '2.5'), (Decimal('3.0'), '3.0'), (Decimal('3.5'), '3.5'), (Decimal('4.0'), '4.0'), (Decimal('4.5'), '4.5'), (Decimal('5.0'), '5.0')], decimal_places=1, max_digits=3, null=True, verbose_name='Nota Esporonamento (0-5)'),
        ),
        migrations.AddField(
            model_name='historicalavaliacaofenotipica',
            name='nota_fruit_set',
            field=models.DecimalField(blank=True, choices=[(Decimal('0.0'), '0.0'), (Decimal('0.5'), '0.5'), (Decimal('1.0'), '1.0'), (Decimal('1.5'), '1.5'), (Decimal('2.0'), '2.0'), (Decimal('2.5'), '2.5'), (Decimal('3.0'), '3.0'), (Decimal('3.5'), '3.5'), (Decimal('4.0'), '4.0'), (Decimal('4.5'), '4.5'), (Decimal('5.0'), '5.0')], decimal_places=1, max_digits=3, null=True, verbose_name='Nota Fruit Set (0-5)'),
        ),
        migrations.AddField(
            model_name='historicalavaliacaofenotipica',
            name='nota_producao',
            field=models.DecimalField(blank=True, choices=[(Decimal('0.0'), '0.0'), (Decimal('0.5'), '0.5'), (Decimal('1.0'), '1.0'), (Decimal('1.5'), '1.5'), (Decimal('2.0'), '2.0'), (Decimal('2.5'), '2.5'), (Decimal('3.0'), '3.0'), (Decimal('3.5'), '3.5'), (Decimal('4.0'), '4.0'), (Decimal('4.5'), '4.5'), (Decimal('5.0'), '5.0')], decimal_places=1, max_digits=3, null=True, verbose_name='Nota Produção (0-5)'),
        ),
    ]
