# Generated by Django 6.0.6 on 2026-07-03 18:39

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macieira', '0015_avaliacaofenotipica_fruto_cacho_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacaofenotipica',
            name='marsonina',
            field=models.DecimalField(blank=True, choices=[(Decimal('0.0'), '0.0'), (Decimal('0.5'), '0.5'), (Decimal('1.0'), '1.0'), (Decimal('1.5'), '1.5'), (Decimal('2.0'), '2.0'), (Decimal('2.5'), '2.5'), (Decimal('3.0'), '3.0'), (Decimal('3.5'), '3.5'), (Decimal('4.0'), '4.0'), (Decimal('4.5'), '4.5'), (Decimal('5.0'), '5.0')], decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MaxValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('5.0'))], verbose_name='Incidência de Marsonina (0-5)'),
        ),
        migrations.AddField(
            model_name='avaliacaofenotipica',
            name='oidio',
            field=models.DecimalField(blank=True, choices=[(Decimal('0.0'), '0.0'), (Decimal('0.5'), '0.5'), (Decimal('1.0'), '1.0'), (Decimal('1.5'), '1.5'), (Decimal('2.0'), '2.0'), (Decimal('2.5'), '2.5'), (Decimal('3.0'), '3.0'), (Decimal('3.5'), '3.5'), (Decimal('4.0'), '4.0'), (Decimal('4.5'), '4.5'), (Decimal('5.0'), '5.0')], decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MaxValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('5.0'))], verbose_name='Incidência de Oídio (0-5)'),
        ),
        migrations.AddField(
            model_name='avaliacaofenotipica',
            name='outras_manchas',
            field=models.DecimalField(blank=True, choices=[(Decimal('0.0'), '0.0'), (Decimal('0.5'), '0.5'), (Decimal('1.0'), '1.0'), (Decimal('1.5'), '1.5'), (Decimal('2.0'), '2.0'), (Decimal('2.5'), '2.5'), (Decimal('3.0'), '3.0'), (Decimal('3.5'), '3.5'), (Decimal('4.0'), '4.0'), (Decimal('4.5'), '4.5'), (Decimal('5.0'), '5.0')], decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MaxValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('5.0'))], verbose_name='Incidência de Outras Manchas (0-5)'),
        ),
        migrations.AddField(
            model_name='avaliacaofenotipica',
            name='podridao_carpelar',
            field=models.DecimalField(blank=True, choices=[(Decimal('0.0'), '0.0'), (Decimal('0.5'), '0.5'), (Decimal('1.0'), '1.0'), (Decimal('1.5'), '1.5'), (Decimal('2.0'), '2.0'), (Decimal('2.5'), '2.5'), (Decimal('3.0'), '3.0'), (Decimal('3.5'), '3.5'), (Decimal('4.0'), '4.0'), (Decimal('4.5'), '4.5'), (Decimal('5.0'), '5.0')], decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MaxValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('5.0'))], verbose_name='Incidência de Podridão Carpelar (0-5)'),
        ),
        migrations.AddField(
            model_name='avaliacaofenotipica',
            name='podridoes_diversas',
            field=models.DecimalField(blank=True, choices=[(Decimal('0.0'), '0.0'), (Decimal('0.5'), '0.5'), (Decimal('1.0'), '1.0'), (Decimal('1.5'), '1.5'), (Decimal('2.0'), '2.0'), (Decimal('2.5'), '2.5'), (Decimal('3.0'), '3.0'), (Decimal('3.5'), '3.5'), (Decimal('4.0'), '4.0'), (Decimal('4.5'), '4.5'), (Decimal('5.0'), '5.0')], decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MaxValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('5.0'))], verbose_name='Incidência de Podridões Diversas (0-5)'),
        ),
        migrations.AddField(
            model_name='historicalavaliacaofenotipica',
            name='marsonina',
            field=models.DecimalField(blank=True, choices=[(Decimal('0.0'), '0.0'), (Decimal('0.5'), '0.5'), (Decimal('1.0'), '1.0'), (Decimal('1.5'), '1.5'), (Decimal('2.0'), '2.0'), (Decimal('2.5'), '2.5'), (Decimal('3.0'), '3.0'), (Decimal('3.5'), '3.5'), (Decimal('4.0'), '4.0'), (Decimal('4.5'), '4.5'), (Decimal('5.0'), '5.0')], decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MaxValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('5.0'))], verbose_name='Incidência de Marsonina (0-5)'),
        ),
        migrations.AddField(
            model_name='historicalavaliacaofenotipica',
            name='oidio',
            field=models.DecimalField(blank=True, choices=[(Decimal('0.0'), '0.0'), (Decimal('0.5'), '0.5'), (Decimal('1.0'), '1.0'), (Decimal('1.5'), '1.5'), (Decimal('2.0'), '2.0'), (Decimal('2.5'), '2.5'), (Decimal('3.0'), '3.0'), (Decimal('3.5'), '3.5'), (Decimal('4.0'), '4.0'), (Decimal('4.5'), '4.5'), (Decimal('5.0'), '5.0')], decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MaxValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('5.0'))], verbose_name='Incidência de Oídio (0-5)'),
        ),
        migrations.AddField(
            model_name='historicalavaliacaofenotipica',
            name='outras_manchas',
            field=models.DecimalField(blank=True, choices=[(Decimal('0.0'), '0.0'), (Decimal('0.5'), '0.5'), (Decimal('1.0'), '1.0'), (Decimal('1.5'), '1.5'), (Decimal('2.0'), '2.0'), (Decimal('2.5'), '2.5'), (Decimal('3.0'), '3.0'), (Decimal('3.5'), '3.5'), (Decimal('4.0'), '4.0'), (Decimal('4.5'), '4.5'), (Decimal('5.0'), '5.0')], decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MaxValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('5.0'))], verbose_name='Incidência de Outras Manchas (0-5)'),
        ),
        migrations.AddField(
            model_name='historicalavaliacaofenotipica',
            name='podridao_carpelar',
            field=models.DecimalField(blank=True, choices=[(Decimal('0.0'), '0.0'), (Decimal('0.5'), '0.5'), (Decimal('1.0'), '1.0'), (Decimal('1.5'), '1.5'), (Decimal('2.0'), '2.0'), (Decimal('2.5'), '2.5'), (Decimal('3.0'), '3.0'), (Decimal('3.5'), '3.5'), (Decimal('4.0'), '4.0'), (Decimal('4.5'), '4.5'), (Decimal('5.0'), '5.0')], decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MaxValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('5.0'))], verbose_name='Incidência de Podridão Carpelar (0-5)'),
        ),
        migrations.AddField(
            model_name='historicalavaliacaofenotipica',
            name='podridoes_diversas',
            field=models.DecimalField(blank=True, choices=[(Decimal('0.0'), '0.0'), (Decimal('0.5'), '0.5'), (Decimal('1.0'), '1.0'), (Decimal('1.5'), '1.5'), (Decimal('2.0'), '2.0'), (Decimal('2.5'), '2.5'), (Decimal('3.0'), '3.0'), (Decimal('3.5'), '3.5'), (Decimal('4.0'), '4.0'), (Decimal('4.5'), '4.5'), (Decimal('5.0'), '5.0')], decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MaxValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('5.0'))], verbose_name='Incidência de Podridões Diversas (0-5)'),
        ),
        migrations.AlterField(
            model_name='avaliacaofenotipica',
            name='incidencia_mfg',
            field=models.DecimalField(blank=True, choices=[(Decimal('0.0'), '0.0'), (Decimal('0.5'), '0.5'), (Decimal('1.0'), '1.0'), (Decimal('1.5'), '1.5'), (Decimal('2.0'), '2.0'), (Decimal('2.5'), '2.5'), (Decimal('3.0'), '3.0'), (Decimal('3.5'), '3.5'), (Decimal('4.0'), '4.0'), (Decimal('4.5'), '4.5'), (Decimal('5.0'), '5.0')], decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('5.0'))], verbose_name='Incidência de Mancha Foliar da Glomerella (0-5)'),
        ),
        migrations.AlterField(
            model_name='avaliacaofenotipica',
            name='incidencia_sarna',
            field=models.DecimalField(blank=True, choices=[(Decimal('0.0'), '0.0'), (Decimal('0.5'), '0.5'), (Decimal('1.0'), '1.0'), (Decimal('1.5'), '1.5'), (Decimal('2.0'), '2.0'), (Decimal('2.5'), '2.5'), (Decimal('3.0'), '3.0'), (Decimal('3.5'), '3.5'), (Decimal('4.0'), '4.0'), (Decimal('4.5'), '4.5'), (Decimal('5.0'), '5.0')], decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('5.0'))], verbose_name='Incidência de Sarna (0-5)'),
        ),
        migrations.AlterField(
            model_name='historicalavaliacaofenotipica',
            name='incidencia_mfg',
            field=models.DecimalField(blank=True, choices=[(Decimal('0.0'), '0.0'), (Decimal('0.5'), '0.5'), (Decimal('1.0'), '1.0'), (Decimal('1.5'), '1.5'), (Decimal('2.0'), '2.0'), (Decimal('2.5'), '2.5'), (Decimal('3.0'), '3.0'), (Decimal('3.5'), '3.5'), (Decimal('4.0'), '4.0'), (Decimal('4.5'), '4.5'), (Decimal('5.0'), '5.0')], decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('5.0'))], verbose_name='Incidência de Mancha Foliar da Glomerella (0-5)'),
        ),
        migrations.AlterField(
            model_name='historicalavaliacaofenotipica',
            name='incidencia_sarna',
            field=models.DecimalField(blank=True, choices=[(Decimal('0.0'), '0.0'), (Decimal('0.5'), '0.5'), (Decimal('1.0'), '1.0'), (Decimal('1.5'), '1.5'), (Decimal('2.0'), '2.0'), (Decimal('2.5'), '2.5'), (Decimal('3.0'), '3.0'), (Decimal('3.5'), '3.5'), (Decimal('4.0'), '4.0'), (Decimal('4.5'), '4.5'), (Decimal('5.0'), '5.0')], decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('5.0'))], verbose_name='Incidência de Sarna (0-5)'),
        ),
    ]
