# Generated by Django 6.0.6 on 2026-07-03 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('macieira', '0016_avaliacaofenotipica_marsonina_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliacaofenotipica',
            old_name='marsonina',
            new_name='incidencia_marsonina',
        ),
        migrations.RenameField(
            model_name='avaliacaofenotipica',
            old_name='oidio',
            new_name='incidencia_oidio',
        ),
        migrations.RenameField(
            model_name='avaliacaofenotipica',
            old_name='outras_manchas',
            new_name='incidencia_outras_manchas',
        ),
        migrations.RenameField(
            model_name='avaliacaofenotipica',
            old_name='podridao_carpelar',
            new_name='incidencia_podridao_carpelar',
        ),
        migrations.RenameField(
            model_name='avaliacaofenotipica',
            old_name='podridoes_diversas',
            new_name='incidencia_podridoes_diversas',
        ),
        migrations.RenameField(
            model_name='historicalavaliacaofenotipica',
            old_name='marsonina',
            new_name='incidencia_marsonina',
        ),
        migrations.RenameField(
            model_name='historicalavaliacaofenotipica',
            old_name='oidio',
            new_name='incidencia_oidio',
        ),
        migrations.RenameField(
            model_name='historicalavaliacaofenotipica',
            old_name='outras_manchas',
            new_name='incidencia_outras_manchas',
        ),
        migrations.RenameField(
            model_name='historicalavaliacaofenotipica',
            old_name='podridao_carpelar',
            new_name='incidencia_podridao_carpelar',
        ),
        migrations.RenameField(
            model_name='historicalavaliacaofenotipica',
            old_name='podridoes_diversas',
            new_name='incidencia_podridoes_diversas',
        ),
    ]
