# Generated by Django 6.0.6 on 2026-07-03 19:57

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macieira', '0017_rename_marsonina_avaliacaofenotipica_incidencia_marsonina_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacaofenotipica',
            name='dias_armazenamento',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Dias de Armazenamento'),
        ),
        migrations.AddField(
            model_name='historicalavaliacaofenotipica',
            name='dias_armazenamento',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Dias de Armazenamento'),
        ),
        migrations.AlterField(
            model_name='avaliacaofenotipica',
            name='incidencia_marsonina',
            field=models.DecimalField(blank=True, choices=[(Decimal('0.0'), '0.0'), (Decimal('0.5'), '0.5'), (Decimal('1.0'), '1.0'), (Decimal('1.5'), '1.5'), (Decimal('2.0'), '2.0'), (Decimal('2.5'), '2.5'), (Decimal('3.0'), '3.0'), (Decimal('3.5'), '3.5'), (Decimal('4.0'), '4.0'), (Decimal('4.5'), '4.5'), (Decimal('5.0'), '5.0')], decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('5.0'))], verbose_name='Incidência de Marsonina (0-5)'),
        ),
        migrations.AlterField(
            model_name='avaliacaofenotipica',
            name='incidencia_oidio',
            field=models.DecimalField(blank=True, choices=[(Decimal('0.0'), '0.0'), (Decimal('0.5'), '0.5'), (Decimal('1.0'), '1.0'), (Decimal('1.5'), '1.5'), (Decimal('2.0'), '2.0'), (Decimal('2.5'), '2.5'), (Decimal('3.0'), '3.0'), (Decimal('3.5'), '3.5'), (Decimal('4.0'), '4.0'), (Decimal('4.5'), '4.5'), (Decimal('5.0'), '5.0')], decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('5.0'))], verbose_name='Incidência de Oídio (0-5)'),
        ),
        migrations.AlterField(
            model_name='avaliacaofenotipica',
            name='incidencia_outras_manchas',
            field=models.DecimalField(blank=True, choices=[(Decimal('0.0'), '0.0'), (Decimal('0.5'), '0.5'), (Decimal('1.0'), '1.0'), (Decimal('1.5'), '1.5'), (Decimal('2.0'), '2.0'), (Decimal('2.5'), '2.5'), (Decimal('3.0'), '3.0'), (Decimal('3.5'), '3.5'), (Decimal('4.0'), '4.0'), (Decimal('4.5'), '4.5'), (Decimal('5.0'), '5.0')], decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('5.0'))], verbose_name='Incidência de Outras Manchas (0-5)'),
        ),
        migrations.AlterField(
            model_name='avaliacaofenotipica',
            name='incidencia_podridao_carpelar',
            field=models.DecimalField(blank=True, choices=[(Decimal('0.0'), '0.0'), (Decimal('0.5'), '0.5'), (Decimal('1.0'), '1.0'), (Decimal('1.5'), '1.5'), (Decimal('2.0'), '2.0'), (Decimal('2.5'), '2.5'), (Decimal('3.0'), '3.0'), (Decimal('3.5'), '3.5'), (Decimal('4.0'), '4.0'), (Decimal('4.5'), '4.5'), (Decimal('5.0'), '5.0')], decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('5.0'))], verbose_name='Incidência de Podridão Carpelar (0-5)'),
        ),
        migrations.AlterField(
            model_name='avaliacaofenotipica',
            name='incidencia_podridoes_diversas',
            field=models.DecimalField(blank=True, choices=[(Decimal('0.0'), '0.0'), (Decimal('0.5'), '0.5'), (Decimal('1.0'), '1.0'), (Decimal('1.5'), '1.5'), (Decimal('2.0'), '2.0'), (Decimal('2.5'), '2.5'), (Decimal('3.0'), '3.0'), (Decimal('3.5'), '3.5'), (Decimal('4.0'), '4.0'), (Decimal('4.5'), '4.5'), (Decimal('5.0'), '5.0')], decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('5.0'))], verbose_name='Incidência de Podridões Diversas (0-5)'),
        ),
        migrations.AlterField(
            model_name='historicalavaliacaofenotipica',
            name='incidencia_marsonina',
            field=models.DecimalField(blank=True, choices=[(Decimal('0.0'), '0.0'), (Decimal('0.5'), '0.5'), (Decimal('1.0'), '1.0'), (Decimal('1.5'), '1.5'), (Decimal('2.0'), '2.0'), (Decimal('2.5'), '2.5'), (Decimal('3.0'), '3.0'), (Decimal('3.5'), '3.5'), (Decimal('4.0'), '4.0'), (Decimal('4.5'), '4.5'), (Decimal('5.0'), '5.0')], decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('5.0'))], verbose_name='Incidência de Marsonina (0-5)'),
        ),
        migrations.AlterField(
            model_name='historicalavaliacaofenotipica',
            name='incidencia_oidio',
            field=models.DecimalField(blank=True, choices=[(Decimal('0.0'), '0.0'), (Decimal('0.5'), '0.5'), (Decimal('1.0'), '1.0'), (Decimal('1.5'), '1.5'), (Decimal('2.0'), '2.0'), (Decimal('2.5'), '2.5'), (Decimal('3.0'), '3.0'), (Decimal('3.5'), '3.5'), (Decimal('4.0'), '4.0'), (Decimal('4.5'), '4.5'), (Decimal('5.0'), '5.0')], decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('5.0'))], verbose_name='Incidência de Oídio (0-5)'),
        ),
        migrations.AlterField(
            model_name='historicalavaliacaofenotipica',
            name='incidencia_outras_manchas',
            field=models.DecimalField(blank=True, choices=[(Decimal('0.0'), '0.0'), (Decimal('0.5'), '0.5'), (Decimal('1.0'), '1.0'), (Decimal('1.5'), '1.5'), (Decimal('2.0'), '2.0'), (Decimal('2.5'), '2.5'), (Decimal('3.0'), '3.0'), (Decimal('3.5'), '3.5'), (Decimal('4.0'), '4.0'), (Decimal('4.5'), '4.5'), (Decimal('5.0'), '5.0')], decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('5.0'))], verbose_name='Incidência de Outras Manchas (0-5)'),
        ),
        migrations.AlterField(
            model_name='historicalavaliacaofenotipica',
            name='incidencia_podridao_carpelar',
            field=models.DecimalField(blank=True, choices=[(Decimal('0.0'), '0.0'), (Decimal('0.5'), '0.5'), (Decimal('1.0'), '1.0'), (Decimal('1.5'), '1.5'), (Decimal('2.0'), '2.0'), (Decimal('2.5'), '2.5'), (Decimal('3.0'), '3.0'), (Decimal('3.5'), '3.5'), (Decimal('4.0'), '4.0'), (Decimal('4.5'), '4.5'), (Decimal('5.0'), '5.0')], decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('5.0'))], verbose_name='Incidência de Podridão Carpelar (0-5)'),
        ),
        migrations.AlterField(
            model_name='historicalavaliacaofenotipica',
            name='incidencia_podridoes_diversas',
            field=models.DecimalField(blank=True, choices=[(Decimal('0.0'), '0.0'), (Decimal('0.5'), '0.5'), (Decimal('1.0'), '1.0'), (Decimal('1.5'), '1.5'), (Decimal('2.0'), '2.0'), (Decimal('2.5'), '2.5'), (Decimal('3.0'), '3.0'), (Decimal('3.5'), '3.5'), (Decimal('4.0'), '4.0'), (Decimal('4.5'), '4.5'), (Decimal('5.0'), '5.0')], decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('5.0'))], verbose_name='Incidência de Podridões Diversas (0-5)'),
        ),
    ]
