# Generated by Django 6.0.6 on 2026-07-03 20:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macieira', '0018_avaliacaofenotipica_dias_armazenamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacaofenotipica',
            name='SST_pos_col',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Sólidos Soluveis Totais na Pós Colheita'),
        ),
        migrations.AddField(
            model_name='avaliacaofenotipica',
            name='firmeza_pos_col',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Firmeza Polpa na Pós Colheita (lbs)'),
        ),
        migrations.AddField(
            model_name='avaliacaofenotipica',
            name='nota_potencial_armazenagem',
            field=models.DecimalField(blank=True, choices=[(Decimal('0.0'), '0.0'), (Decimal('0.5'), '0.5'), (Decimal('1.0'), '1.0'), (Decimal('1.5'), '1.5'), (Decimal('2.0'), '2.0'), (Decimal('2.5'), '2.5'), (Decimal('3.0'), '3.0'), (Decimal('3.5'), '3.5'), (Decimal('4.0'), '4.0'), (Decimal('4.5'), '4.5'), (Decimal('5.0'), '5.0')], decimal_places=1, max_digits=3, null=True, verbose_name='Nota para o Potêncial de armazenagem (0-5)'),
        ),
        migrations.AddField(
            model_name='historicalavaliacaofenotipica',
            name='SST_pos_col',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Sólidos Soluveis Totais na Pós Colheita'),
        ),
        migrations.AddField(
            model_name='historicalavaliacaofenotipica',
            name='firmeza_pos_col',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Firmeza Polpa na Pós Colheita (lbs)'),
        ),
        migrations.AddField(
            model_name='historicalavaliacaofenotipica',
            name='nota_potencial_armazenagem',
            field=models.DecimalField(blank=True, choices=[(Decimal('0.0'), '0.0'), (Decimal('0.5'), '0.5'), (Decimal('1.0'), '1.0'), (Decimal('1.5'), '1.5'), (Decimal('2.0'), '2.0'), (Decimal('2.5'), '2.5'), (Decimal('3.0'), '3.0'), (Decimal('3.5'), '3.5'), (Decimal('4.0'), '4.0'), (Decimal('4.5'), '4.5'), (Decimal('5.0'), '5.0')], decimal_places=1, max_digits=3, null=True, verbose_name='Nota para o Potêncial de armazenagem (0-5)'),
        ),
    ]
