# Generated by Django 6.0.6 on 2026-07-08 13:01

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macieira', '0019_avaliacaofenotipica_sst_pos_col_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacaofenotipica',
            options={'ordering': ['-data_avaliacao'], 'verbose_name': 'Avaliação Fenotípica', 'verbose_name_plural': 'Avaliações Fenotípicas'},
        ),
        migrations.RemoveField(
            model_name='cruzamento',
            name='num_bloco_hibridos',
        ),
        migrations.RemoveField(
            model_name='historicalcruzamento',
            name='num_bloco_hibridos',
        ),
        migrations.AddField(
            model_name='avaliacaofenotipica',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='avaliacaofenotipica',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cruzamento',
            name='num_bloco_pre_selecao',
            field=models.IntegerField(blank=True, null=True, verbose_name='N°. Plantas no Bloco de Pré-Seleção'),
        ),
        migrations.AddField(
            model_name='genotipo',
            name='ano_selecao',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='Ano de Seleção'),
        ),
        migrations.AddField(
            model_name='genotipo',
            name='codigo_pre_selecao',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='Cód. Pré-Seleção'),
        ),
        migrations.AddField(
            model_name='genotipo',
            name='codigo_selecao',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='Cód. Seleção'),
        ),
        migrations.AddField(
            model_name='historicalavaliacaofenotipica',
            name='atualizado_em',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalavaliacaofenotipica',
            name='criado_em',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalcruzamento',
            name='num_bloco_pre_selecao',
            field=models.IntegerField(blank=True, null=True, verbose_name='N°. Plantas no Bloco de Pré-Seleção'),
        ),
        migrations.AddField(
            model_name='historicalgenotipo',
            name='ano_selecao',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='Ano de Seleção'),
        ),
        migrations.AddField(
            model_name='historicalgenotipo',
            name='codigo_pre_selecao',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='Cód. Pré-Seleção'),
        ),
        migrations.AddField(
            model_name='historicalgenotipo',
            name='codigo_selecao',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='Cód. Seleção'),
        ),
        migrations.AlterField(
            model_name='ambiente',
            name='tipo',
            field=models.CharField(choices=[('MATRIZEIRO', 'Matrizeiro'), ('BLOCO_PRE_SELECAO', 'Bloco de Pré-Seleção'), ('BLOCO_SELECOES', 'Bloco de Seleções'), ('POMAR_PARENTAIS', 'Pomar de Parentais'), ('BAG', 'BAG'), ('CASA_VEGETACAO', 'Casa de Vegetação')], max_length=30, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='avaliacaofenotipica',
            name='SST_pos_col',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='SST Pós Colheita (°Brix)'),
        ),
        migrations.AlterField(
            model_name='avaliacaofenotipica',
            name='cork_spot',
            field=models.CharField(blank=True, choices=[('AUSENTE', 'Ausente'), ('PRESENTE', 'Presente (em baixa intensidade)'), ('INTENSO', 'Muito Presente')], max_length=8, null=True, verbose_name='Cork Spot'),
        ),
        migrations.AlterField(
            model_name='avaliacaofenotipica',
            name='dias_armazenamento',
            field=models.IntegerField(blank=True, null=True, verbose_name='Dias Armazenamento'),
        ),
        migrations.AlterField(
            model_name='avaliacaofenotipica',
            name='firmeza_pos_col',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Firmeza Pós Colheita (lbs)'),
        ),
        migrations.AlterField(
            model_name='avaliacaofenotipica',
            name='foto_frutos_colhidos',
            field=models.ImageField(blank=True, null=True, upload_to='avaliacoes/frutos/', verbose_name='Foto Frutos Colhidos'),
        ),
        migrations.AlterField(
            model_name='avaliacaofenotipica',
            name='foto_sintomas',
            field=models.ImageField(blank=True, null=True, upload_to='avaliacoes/sintomas/', verbose_name='Foto Sintomas/Outros'),
        ),
        migrations.AlterField(
            model_name='avaliacaofenotipica',
            name='fruto_cacho',
            field=models.IntegerField(blank=True, null=True, verbose_name='N° Frutos/Cacho'),
        ),
        migrations.AlterField(
            model_name='avaliacaofenotipica',
            name='incidencia_marsonina',
            field=models.CharField(blank=True, choices=[('AUSENTE', 'Ausente'), ('PRESENTE', 'Presente (em baixa intensidade)'), ('INTENSO', 'Muito Presente')], max_length=8, null=True, verbose_name='Incidência Marsonina'),
        ),
        migrations.AlterField(
            model_name='avaliacaofenotipica',
            name='incidencia_mfg',
            field=models.CharField(blank=True, choices=[('AUSENTE', 'Ausente'), ('PRESENTE', 'Presente (em baixa intensidade)'), ('INTENSO', 'Muito Presente')], max_length=8, null=True, verbose_name='Incidência MFG'),
        ),
        migrations.AlterField(
            model_name='avaliacaofenotipica',
            name='incidencia_oidio',
            field=models.CharField(blank=True, choices=[('AUSENTE', 'Ausente'), ('PRESENTE', 'Presente (em baixa intensidade)'), ('INTENSO', 'Muito Presente')], max_length=8, null=True, verbose_name='Incidência Oídio'),
        ),
        migrations.AlterField(
            model_name='avaliacaofenotipica',
            name='incidencia_outras_manchas',
            field=models.CharField(blank=True, choices=[('AUSENTE', 'Ausente'), ('PRESENTE', 'Presente (em baixa intensidade)'), ('INTENSO', 'Muito Presente')], max_length=8, null=True, verbose_name='Incidência Outras Manchas'),
        ),
        migrations.AlterField(
            model_name='avaliacaofenotipica',
            name='incidencia_podridao_carpelar',
            field=models.CharField(blank=True, choices=[('AUSENTE', 'Ausente'), ('PRESENTE', 'Presente (em baixa intensidade)'), ('INTENSO', 'Muito Presente')], max_length=8, null=True, verbose_name='Incidência Podridão Carpelar'),
        ),
        migrations.AlterField(
            model_name='avaliacaofenotipica',
            name='incidencia_podridoes_diversas',
            field=models.CharField(blank=True, choices=[('AUSENTE', 'Ausente'), ('PRESENTE', 'Presente (em baixa intensidade)'), ('INTENSO', 'Muito Presente')], max_length=8, null=True, verbose_name='Incidência Podridões Diversas'),
        ),
        migrations.AlterField(
            model_name='avaliacaofenotipica',
            name='incidencia_sarna',
            field=models.CharField(blank=True, choices=[('AUSENTE', 'Ausente'), ('PRESENTE', 'Presente (em baixa intensidade)'), ('INTENSO', 'Muito Presente')], max_length=8, null=True, verbose_name='Incidência Sarna'),
        ),
        migrations.AlterField(
            model_name='avaliacaofenotipica',
            name='nota_potencial_armazenagem',
            field=models.DecimalField(blank=True, choices=[(Decimal('0.0'), '0.0'), (Decimal('0.5'), '0.5'), (Decimal('1.0'), '1.0'), (Decimal('1.5'), '1.5'), (Decimal('2.0'), '2.0'), (Decimal('2.5'), '2.5'), (Decimal('3.0'), '3.0'), (Decimal('3.5'), '3.5'), (Decimal('4.0'), '4.0'), (Decimal('4.5'), '4.5'), (Decimal('5.0'), '5.0')], decimal_places=1, max_digits=3, null=True, verbose_name='Nota Potencial Armazenagem (0-5)'),
        ),
        migrations.AlterField(
            model_name='avaliacaofenotipica',
            name='nota_vigor',
            field=models.DecimalField(blank=True, choices=[(Decimal('0.0'), '0.0'), (Decimal('0.5'), '0.5'), (Decimal('1.0'), '1.0'), (Decimal('1.5'), '1.5'), (Decimal('2.0'), '2.0'), (Decimal('2.5'), '2.5'), (Decimal('3.0'), '3.0'), (Decimal('3.5'), '3.5'), (Decimal('4.0'), '4.0'), (Decimal('4.5'), '4.5'), (Decimal('5.0'), '5.0')], decimal_places=1, max_digits=3, null=True, verbose_name='Nota Vigor (0-5)'),
        ),
        migrations.AlterField(
            model_name='avaliacaofenotipica',
            name='pingo_mel',
            field=models.CharField(blank=True, choices=[('AUSENTE', 'Ausente'), ('PRESENTE', 'Presente (em baixa intensidade)'), ('INTENSO', 'Muito Presente')], max_length=8, null=True, verbose_name='Pingo de Mel'),
        ),
        migrations.AlterField(
            model_name='avaliacaofenotipica',
            name='produtividade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Produtividade (kg/planta)'),
        ),
        migrations.AlterField(
            model_name='avaliacaofenotipica',
            name='russting',
            field=models.CharField(blank=True, choices=[('AUSENTE', 'Ausente'), ('PRESENTE', 'Presente (em baixa intensidade)'), ('INTENSO', 'Muito Presente')], max_length=8, null=True, verbose_name='Russting'),
        ),
        migrations.AlterField(
            model_name='cruzamento',
            name='genitor_feminino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cruzamentos_como_mae', to='macieira.genotipo', verbose_name='Genitor Feminino (Mãe)'),
        ),
        migrations.AlterField(
            model_name='cruzamento',
            name='genitor_masculino',
            field=models.ForeignKey(blank=True, help_text='Deixe em branco para Polinização Livre', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cruzamentos_como_pai', to='macieira.genotipo', verbose_name='Genitor Masculino (Pai)'),
        ),
        migrations.AlterField(
            model_name='cruzamento',
            name='identificador',
            field=models.CharField(help_text='Número sequencial do cruzamento (ex: 263)', max_length=50, unique=True, verbose_name='Nº Cruzamento'),
        ),
        migrations.AlterField(
            model_name='cruzamento',
            name='num_matrizeiro',
            field=models.IntegerField(blank=True, null=True, verbose_name='N° Plantas no Matrizeiro'),
        ),
        migrations.AlterField(
            model_name='cruzamento',
            name='num_plantulas_formadas',
            field=models.IntegerField(blank=True, null=True, verbose_name='N° Plântulas Formadas'),
        ),
        migrations.AlterField(
            model_name='genotipo',
            name='genotipo_original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mutacoes', to='macieira.genotipo', verbose_name='Genótipo Original (para mutações/promoções)'),
        ),
        migrations.AlterField(
            model_name='genotipo',
            name='tipo',
            field=models.CharField(choices=[('PARENTAL', 'Parental'), ('SEEDLING', 'Seedling'), ('PRE_SELECAO', 'Pré-Seleção'), ('SELECAO', 'Seleção'), ('CULTIVAR', 'Cultivar'), ('MUTANTE', 'Mutante'), ('ACESSO_BAG', 'Acesso BAG')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='historicalambiente',
            name='tipo',
            field=models.CharField(choices=[('MATRIZEIRO', 'Matrizeiro'), ('BLOCO_PRE_SELECAO', 'Bloco de Pré-Seleção'), ('BLOCO_SELECOES', 'Bloco de Seleções'), ('POMAR_PARENTAIS', 'Pomar de Parentais'), ('BAG', 'BAG'), ('CASA_VEGETACAO', 'Casa de Vegetação')], max_length=30, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='historicalavaliacaofenotipica',
            name='SST_pos_col',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='SST Pós Colheita (°Brix)'),
        ),
        migrations.AlterField(
            model_name='historicalavaliacaofenotipica',
            name='cork_spot',
            field=models.CharField(blank=True, choices=[('AUSENTE', 'Ausente'), ('PRESENTE', 'Presente (em baixa intensidade)'), ('INTENSO', 'Muito Presente')], max_length=8, null=True, verbose_name='Cork Spot'),
        ),
        migrations.AlterField(
            model_name='historicalavaliacaofenotipica',
            name='dias_armazenamento',
            field=models.IntegerField(blank=True, null=True, verbose_name='Dias Armazenamento'),
        ),
        migrations.AlterField(
            model_name='historicalavaliacaofenotipica',
            name='firmeza_pos_col',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Firmeza Pós Colheita (lbs)'),
        ),
        migrations.AlterField(
            model_name='historicalavaliacaofenotipica',
            name='foto_frutos_colhidos',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Foto Frutos Colhidos'),
        ),
        migrations.AlterField(
            model_name='historicalavaliacaofenotipica',
            name='foto_sintomas',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Foto Sintomas/Outros'),
        ),
        migrations.AlterField(
            model_name='historicalavaliacaofenotipica',
            name='fruto_cacho',
            field=models.IntegerField(blank=True, null=True, verbose_name='N° Frutos/Cacho'),
        ),
        migrations.AlterField(
            model_name='historicalavaliacaofenotipica',
            name='incidencia_marsonina',
            field=models.CharField(blank=True, choices=[('AUSENTE', 'Ausente'), ('PRESENTE', 'Presente (em baixa intensidade)'), ('INTENSO', 'Muito Presente')], max_length=8, null=True, verbose_name='Incidência Marsonina'),
        ),
        migrations.AlterField(
            model_name='historicalavaliacaofenotipica',
            name='incidencia_mfg',
            field=models.CharField(blank=True, choices=[('AUSENTE', 'Ausente'), ('PRESENTE', 'Presente (em baixa intensidade)'), ('INTENSO', 'Muito Presente')], max_length=8, null=True, verbose_name='Incidência MFG'),
        ),
        migrations.AlterField(
            model_name='historicalavaliacaofenotipica',
            name='incidencia_oidio',
            field=models.CharField(blank=True, choices=[('AUSENTE', 'Ausente'), ('PRESENTE', 'Presente (em baixa intensidade)'), ('INTENSO', 'Muito Presente')], max_length=8, null=True, verbose_name='Incidência Oídio'),
        ),
        migrations.AlterField(
            model_name='historicalavaliacaofenotipica',
            name='incidencia_outras_manchas',
            field=models.CharField(blank=True, choices=[('AUSENTE', 'Ausente'), ('PRESENTE', 'Presente (em baixa intensidade)'), ('INTENSO', 'Muito Presente')], max_length=8, null=True, verbose_name='Incidência Outras Manchas'),
        ),
        migrations.AlterField(
            model_name='historicalavaliacaofenotipica',
            name='incidencia_podridao_carpelar',
            field=models.CharField(blank=True, choices=[('AUSENTE', 'Ausente'), ('PRESENTE', 'Presente (em baixa intensidade)'), ('INTENSO', 'Muito Presente')], max_length=8, null=True, verbose_name='Incidência Podridão Carpelar'),
        ),
        migrations.AlterField(
            model_name='historicalavaliacaofenotipica',
            name='incidencia_podridoes_diversas',
            field=models.CharField(blank=True, choices=[('AUSENTE', 'Ausente'), ('PRESENTE', 'Presente (em baixa intensidade)'), ('INTENSO', 'Muito Presente')], max_length=8, null=True, verbose_name='Incidência Podridões Diversas'),
        ),
        migrations.AlterField(
            model_name='historicalavaliacaofenotipica',
            name='incidencia_sarna',
            field=models.CharField(blank=True, choices=[('AUSENTE', 'Ausente'), ('PRESENTE', 'Presente (em baixa intensidade)'), ('INTENSO', 'Muito Presente')], max_length=8, null=True, verbose_name='Incidência Sarna'),
        ),
        migrations.AlterField(
            model_name='historicalavaliacaofenotipica',
            name='nota_potencial_armazenagem',
            field=models.DecimalField(blank=True, choices=[(Decimal('0.0'), '0.0'), (Decimal('0.5'), '0.5'), (Decimal('1.0'), '1.0'), (Decimal('1.5'), '1.5'), (Decimal('2.0'), '2.0'), (Decimal('2.5'), '2.5'), (Decimal('3.0'), '3.0'), (Decimal('3.5'), '3.5'), (Decimal('4.0'), '4.0'), (Decimal('4.5'), '4.5'), (Decimal('5.0'), '5.0')], decimal_places=1, max_digits=3, null=True, verbose_name='Nota Potencial Armazenagem (0-5)'),
        ),
        migrations.AlterField(
            model_name='historicalavaliacaofenotipica',
            name='nota_vigor',
            field=models.DecimalField(blank=True, choices=[(Decimal('0.0'), '0.0'), (Decimal('0.5'), '0.5'), (Decimal('1.0'), '1.0'), (Decimal('1.5'), '1.5'), (Decimal('2.0'), '2.0'), (Decimal('2.5'), '2.5'), (Decimal('3.0'), '3.0'), (Decimal('3.5'), '3.5'), (Decimal('4.0'), '4.0'), (Decimal('4.5'), '4.5'), (Decimal('5.0'), '5.0')], decimal_places=1, max_digits=3, null=True, verbose_name='Nota Vigor (0-5)'),
        ),
        migrations.AlterField(
            model_name='historicalavaliacaofenotipica',
            name='pingo_mel',
            field=models.CharField(blank=True, choices=[('AUSENTE', 'Ausente'), ('PRESENTE', 'Presente (em baixa intensidade)'), ('INTENSO', 'Muito Presente')], max_length=8, null=True, verbose_name='Pingo de Mel'),
        ),
        migrations.AlterField(
            model_name='historicalavaliacaofenotipica',
            name='produtividade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Produtividade (kg/planta)'),
        ),
        migrations.AlterField(
            model_name='historicalavaliacaofenotipica',
            name='russting',
            field=models.CharField(blank=True, choices=[('AUSENTE', 'Ausente'), ('PRESENTE', 'Presente (em baixa intensidade)'), ('INTENSO', 'Muito Presente')], max_length=8, null=True, verbose_name='Russting'),
        ),
        migrations.AlterField(
            model_name='historicalcruzamento',
            name='genitor_feminino',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='macieira.genotipo', verbose_name='Genitor Feminino (Mãe)'),
        ),
        migrations.AlterField(
            model_name='historicalcruzamento',
            name='genitor_masculino',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Deixe em branco para Polinização Livre', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='macieira.genotipo', verbose_name='Genitor Masculino (Pai)'),
        ),
        migrations.AlterField(
            model_name='historicalcruzamento',
            name='identificador',
            field=models.CharField(db_index=True, help_text='Número sequencial do cruzamento (ex: 263)', max_length=50, verbose_name='Nº Cruzamento'),
        ),
        migrations.AlterField(
            model_name='historicalcruzamento',
            name='num_matrizeiro',
            field=models.IntegerField(blank=True, null=True, verbose_name='N° Plantas no Matrizeiro'),
        ),
        migrations.AlterField(
            model_name='historicalcruzamento',
            name='num_plantulas_formadas',
            field=models.IntegerField(blank=True, null=True, verbose_name='N° Plântulas Formadas'),
        ),
        migrations.AlterField(
            model_name='historicalgenotipo',
            name='genotipo_original',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='macieira.genotipo', verbose_name='Genótipo Original (para mutações/promoções)'),
        ),
        migrations.AlterField(
            model_name='historicalgenotipo',
            name='tipo',
            field=models.CharField(choices=[('PARENTAL', 'Parental'), ('SEEDLING', 'Seedling'), ('PRE_SELECAO', 'Pré-Seleção'), ('SELECAO', 'Seleção'), ('CULTIVAR', 'Cultivar'), ('MUTANTE', 'Mutante'), ('ACESSO_BAG', 'Acesso BAG')], max_length=20, verbose_name='Tipo'),
        ),
    ]
